In [1]:
import numpy
x = [[0, 0.076,0.153],
    [0.153, 0.230, 0.923],
    [1, 0.307, 0.384],
    [0.923, 0.461, 0.538],
    [0.307, 0.76, 0.923],
     [0.615, 0.692, 0.923],
     [0.769, 0.846, 1.076]]
x = numpy.array(x)
xx = numpy.reshape(x, (x.shape[0], x.shape[1], 1))
from keras.models import Sequential
from keras.layers import LSTM, Dense
model = Sequential()
model.add(LSTM(units = 1, input_shape=(3, 1)))
model.add(Dense(14))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['acc'])

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


In [2]:
import tensorflow
from keras import backend as K
    
# with a Sequential model
get_1st_layer_output = K.function([model.layers[0].input],
                                  [model.layers[0].output])
layer_output = get_1st_layer_output([xx])[0]

In [3]:
xx.shape

(7, 3, 1)

In [4]:
layer_output


array([[-0.01614695],
       [-0.09328092],
       [-0.07744108],
       [-0.09351535],
       [-0.11985636],
       [-0.12463342],
       [-0.14527683]], dtype=float32)

In [5]:
model.layers[0].get_weights()

[array([[-0.04807365, -1.0889516 , -0.3113991 ,  0.3983611 ]],
       dtype=float32),
 array([[-0.52991545,  0.11155427, -0.05521049, -0.83886653]],
       dtype=float32),
 array([0., 1., 0., 0.], dtype=float32)]

In [6]:
from keras.layers import SimpleRNN
from keras.models import Sequential
from keras.layers import LSTM, Dense
modelss = Sequential()
modelss.add(SimpleRNN(units = 1, input_shape=(3, 1)))
modelss.add(Dense(14))
modelss.compile(loss='mean_squared_error', optimizer='adam', metrics=['acc'])

In [7]:
get_1st_layer_output = K.function([modelss.layers[0].input],
                                  [modelss.layers[0].output])
layer_output = get_1st_layer_output([xx])[0]

In [8]:
layer_output

array([[0.08733327],
       [0.7434532 ],
       [0.7009317 ],
       [0.69750136],
       [0.5107094 ],
       [0.699779  ],
       [0.74824494]], dtype=float32)

In [12]:
wt = modelss.layers[0].weights
wn = list(map(lambda xx:xx.name, wt))

In [13]:
wn

['simple_rnn_1/kernel:0',
 'simple_rnn_1/recurrent_kernel:0',
 'simple_rnn_1/bias:0']

In [17]:
units = 1
W = model.layers[0].get_weights()[0]
U = model.layers[0].get_weights()[1]
b = model.layers[0].get_weights()[2]

W_i = W[:, :units]
W_f = W[:, units: units * 2]
W_c = W[:, units * 2: units * 3]
W_o = W[:, units * 3:]

U_i = U[:, :units]
U_f = U[:, units: units * 2]
U_c = U[:, units * 2: units * 3]
U_o = U[:, units * 3:]

b_i = b[:units]
b_f = b[units: units * 2]
b_c = b[units * 2: units * 3]
b_o = b[units * 3:]


In [18]:
W_i


array([[-0.04807365]], dtype=float32)